# Generated by Django 6.0.7 on 2026-07-27 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(default='maize', max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('harvest_date', models.DateField()),
                ('moisture_content', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage', max_digits=5, null=True)),
                ('quality_grade', models.CharField(blank=True, help_text='e.g., A, B, C', max_length=20)),
                ('is_sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to=settings.AUTH_USER_MODEL)),
                ('storage_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='harvests.storagemethod')),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_type', models.CharField(choices=[('spoilage', 'Spoilage'), ('insect', 'Insect Damage'), ('rodent', 'Rodent Damage'), ('theft', 'Theft'), ('other', 'Other')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='harvests.harvest')),
            ],
        ),
    ]
