# Generated by Django 6.0.7 on 2026-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='loss',
            options={'ordering': ['-reported_date']},
        ),
        migrations.AlterModelOptions(
            name='storagemethod',
            options={'ordering': ['name']},
        ),
    ]
