# Generated by Django 6.0.7 on 2026-08-06 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="User's display name", max_length=100)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('partner', 'Partner / Investor'), ('other', 'Community Member')], default='farmer', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating between 1 and 5 stars')),
                ('category', models.CharField(choices=[('general', 'General Experience'), ('post_harvest', 'Post-Harvest Management'), ('marketplace', 'Marketplace & Trade'), ('finance', 'Grants & Financial Inclusion'), ('chatbot', 'AI Agribot Assistant'), ('usability', 'App Usability & Performance')], default='general', max_length=30)),
                ('comment', models.TextField(help_text='User feedback comments and suggestions')),
                ('is_public', models.BooleanField(default=True, help_text='Show in public testimonials on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
