# Generated by Django 6.0.7 on 2026-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['-application_date']},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-application_date']},
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['-payment_date']},
        ),
    ]
