# Generated by Django 6.0.7 on 2026-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo of your maize', null=True, upload_to='listings/'),
        ),
    ]
