# Generated by Django 6.0.7 on 2026-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
    ]
